# Generated by Django 4.2.26 on 2025-11-26 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название мероприятия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_at', models.DateTimeField(verbose_name='Дата начала')),
                ('end_at', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=False, verbose_name='Мероприятие активно')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('announcements_enabled', models.BooleanField(default=True, verbose_name='Рассылки включены')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='Telegram user id')),
                ('tg_username', models.CharField(blank=True, max_length=64, verbose_name='Ник в Telegram')),
                ('first_name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='Фамилия')),
                ('is_organizer', models.BooleanField(default=False, verbose_name='Организатор')),
                ('is_speaker', models.BooleanField(default=False, verbose_name='Докладчик')),
                ('wants_notifications', models.BooleanField(default=True, verbose_name='Получать уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название площадки')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название доклада')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_at', models.DateTimeField(verbose_name='Начало доклада')),
                ('end_at', models.DateTimeField(verbose_name='Конец доклада')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в программе')),
                ('room', models.CharField(blank=True, max_length=64, verbose_name='Зал/комната')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('in_progress', 'В процессе'), ('done', 'Завершено'), ('cancelled', 'Отменено')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущий доклад')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='meetbot.event', verbose_name='Мероприятие')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talks', to='meetbot.participant', verbose_name='Докладчик')),
            ],
            options={
                'ordering': ['event_id', 'order', 'start_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('status', models.CharField(choices=[('pending', 'Получен'), ('sent', 'Отправлен спикеру'), ('answered', 'Отвечен'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус')),
                ('answer_text', models.TextField(blank=True, verbose_name='Ответ спикера')),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('speaker_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID сообщения в чате спикера')),
                ('attendee_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID сообщения для автора')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='meetbot.participant', verbose_name='Автор вопроса')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='meetbot.talk', verbose_name='Доклад')),
            ],
            options={
                'ordering': ['-asked_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=64, verbose_name='Роль')),
                ('company', models.CharField(blank=True, max_length=128, verbose_name='Компания')),
                ('stack', models.CharField(blank=True, max_length=255, verbose_name='Технический стек')),
                ('interests', models.TextField(blank=True, verbose_name='Интересы')),
                ('goals', models.TextField(blank=True, verbose_name='Цель знакомства')),
                ('contact', models.CharField(help_text='@username или ссылка', max_length=128, verbose_name='Контакт в Telegram')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networking_profiles', to='meetbot.event', verbose_name='Мероприятие')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networking_profiles', to='meetbot.participant', verbose_name='Участник')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('participant', 'event')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='current_talk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meetbot.talk', verbose_name='Текущий доклад'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='meetbot.place', verbose_name='Место проведения'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=8, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('waiting_for_capture', 'Ожидает подтверждения'), ('succeeded', 'Успешно'), ('failed', 'Неуспешно'), ('canceled', 'Отменено')], default='pending', max_length=32, verbose_name='Статус')),
                ('provider', models.CharField(blank=True, default='yookassa', max_length=50, verbose_name='Провайдер')),
                ('yookassa_payment_id', models.CharField(blank=True, help_text='payment.id из ответа YooKassa', max_length=64, verbose_name='ID платежа YooKassa')),
                ('idempotence_key', models.CharField(blank=True, help_text='для повторных запросов create/capture', max_length=64, verbose_name='Idempotence-Key')),
                ('confirmation_url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка для оплаты')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Назначение платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='meetbot.event', verbose_name='Мероприятие')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='meetbot.participant', verbose_name='Отправитель')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('event', 'Обновления мероприятия'), ('future', 'Будущие мероприятия')], default='event', max_length=16, verbose_name='Тип подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='meetbot.event', verbose_name='Мероприятие')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='meetbot.participant', verbose_name='Участник')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('participant', 'event', 'subscription_type')},
            },
        ),
        migrations.CreateModel(
            name='NetworkingMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Отправлено'), ('accepted', 'Принято'), ('skipped', 'Пропущено')], default='pending', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networking_matches', to='meetbot.event', verbose_name='Мероприятие')),
                ('source_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_matches', to='meetbot.networkingprofile', verbose_name='Анкета инициатора')),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_matches', to='meetbot.networkingprofile', verbose_name='Предложенная анкета')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'source_profile', 'target_profile')},
            },
        ),
    ]
